### ISSUE TITLE
Feature Request: Copy Project

### ISSUE THREAD

**Issue by zimmer62** [wreality/laser-gcode-app#15]
If you have an existing project, and would like a copy, under a different name.  One reason to do this, would be if you had nearly identical operations, with one operation different, or using different laser settings.

**Comment by wreality** [comment]
Should be added on laserbeta shortly.

**Comment by zimmer62** [comment]
Was this duplicate operation?  I was thinking more along the lines of
duplicating a project.  I have several operations in a project, And I need
to change the cut to an engrave for just one of the 3 operations.  I was
hoping the copy the project to a second project

Joe

**Comment by wreality** [comment]
It's both. Implementing one was just as easy as implementing both. :-)
