### ISSUE TITLE
Feed of 6000's and and reset to home between operations

### ISSUE THREAD

**Issue by zimmer62** [wreality/laser-gcode-app#17]
The g code still has a feed rate of 6000 even when the max is set much lower.  The current state of the machine this causes the motors to skip steps.

It also seems to return to origin between each operation.

**Comment by wreality** [comment]
Even with traversal rate and home before set?

And just to be doubly sure, did you regenerate the gcode ?

—

**Comment by wreality** [comment]
Can you send me a link to the project you were working with that didn't generate code correctly ?

**Comment by wreality** [comment]
Found the issue I think.  There was a setting that was incorrect on laserbeta.  Closing for now, feel free to reopen in regenerating code doesn't fix it.
