### ISSUE TITLE
M80 not being added

### ISSUE THREAD

**Issue by zimmer62** [wreality/laser-gcode-app#18]
I was having problems last night where the laser would not fire when running the gcode unless I did a test fire first.

Turns out M80 was missing from the file... should laserbeta automatically add that?

**Comment by wreality** [comment]
Hmm.  It should be added.  I'll look into it.

**Comment by wreality** [comment]
Yup there was indeed a bug.  Should be fixed on laserbeta momentarily as soon as the travis builds complete successfully.

**Comment by zimmer62** [comment]
Good Job Travis! haha
